# Generated by Django 5.1.6 on 2025-05-14 10:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_section', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phonenumber', models.CharField(max_length=15)),
                ('district', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=120)),
                ('purpose', models.CharField(max_length=100)),
                ('mode_of_purpose', models.CharField(max_length=100)),
                ('message', models.TextField(max_length=250)),
                ('status', models.CharField(default='Pending', max_length=100)),
                ('stage', models.CharField(default='Not Opened', max_length=100)),
                ('closed_date', models.DateField(blank=True, null=True)),
                ('follower', models.CharField(default='Nil', max_length=100)),
                ('staff_id', models.IntegerField(default=0)),
                ('staff_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth_section.sales_manager_reg')),
            ],
        ),
        migrations.CreateModel(
            name='LeadCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.CharField(max_length=100)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_category', to='leads_section.leads')),
            ],
        ),
    ]
