# Generated by Django 5.1.6 on 2025-05-16 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databank_section', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databank',
            name='area_in_sqft',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
