# Generated by Django 5.1.6 on 2025-05-17 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_section', '0001_initial'),
        ('databank_section', '0002_alter_databank_area_in_sqft'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='databank',
            name='email',
        ),
        migrations.RemoveField(
            model_name='databank',
            name='follower',
        ),
        migrations.RemoveField(
            model_name='databank',
            name='lead',
        ),
        migrations.RemoveField(
            model_name='databank',
            name='location_proposal_district',
        ),
        migrations.RemoveField(
            model_name='databank',
            name='location_proposal_place',
        ),
        migrations.AddField(
            model_name='databank',
            name='advance_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='databank',
            name='area_in_cent',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='databank',
            name='closed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='databank',
            name='location_preferences',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='databank',
            name='stage',
            field=models.CharField(default='Not Opened', max_length=100),
        ),
        migrations.AddField(
            model_name='databank',
            name='status',
            field=models.CharField(default='Pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='databank',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='databank',
            name='building_bhk',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='databank',
            name='demand_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='databank',
            name='number_of_floors',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='LeadDataFollower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_section.sales_manager_reg')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databank_section.databank')),
            ],
        ),
    ]
